name: Build, Test, Dockerize, Deploy, and Destroy .NET Application

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Destroy Terraform infrastructure"
        required: false
        default: "false"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: f-eighty7/fantasychas-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .
          docker push $REGISTRY/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure VM using Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

  destroy:
    runs-on: ubuntu-latest
    needs: [deploy]

    if: ${{ github.event.inputs.destroy == 'true' && success() }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Destroy Terraform resources
        run: terraform -chdir=terraform destroy -auto-approve
