name: Build, Test, Dockerize, Deploy, and Destroy .NET Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy Terraform-managed resources'
        required: true
        default: 'false'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: f-eighty7/fantasychas-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if resource group exists
        id: check_rg
        run: |
          exists=$(az group exists --name rg-fantasychas)
          echo "::set-output name=exists::$exists"

      - name: Import resource group
        if: steps.check_rg.outputs.exists == 'true'
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/
          338906d8-4c3f-4170-8dfe-09d3ec8664a6/resourceGroups/rg-fantasychas

      - name: Check if virtual network exists
        id: check_vnet
        run: |
          exists=$(az network vnet show --name vnet-fantasychas --resource-group rg-fantasychas --query "name" -o tsv)
          echo "::set-output name=exists::$exists"

      - name: Import virtual network
        if: steps.check_vnet.outputs.exists == 'vnet-fantasychas'
        run: |
          terraform import azurerm_virtual_network.vnet /subscriptions/
          338906d8-4c3f-4170-8dfe-09d3ec8664a6/resourceGroups/rg-fantasychas/providers/Microsoft.Network/virtualNetworks/vnet-fantasychas

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ghcr_username: ${{ secrets.GHCR_USERNAME }}
          TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN }}

  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.destroy == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          TF_VAR_ghcr_username: ${{ secrets.GHCR_USERNAME }}
          TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN }}
