name: Build, Dockerize, and Deploy .NET Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: f-eighty7/fantasychas-backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the application
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Set Docker image details as output
        id: vars
        run: |
          echo "::set-output name=docker_image::${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          echo "::set-output name=docker_registry_server::${{ env.REGISTRY }}"
          echo "::set-output name=docker_registry_username::${{ github.actor }}"
          echo "::set-output name=docker_registry_password::${{ secrets.GITHUB_TOKEN }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
        env:
          TF_VAR_docker_image: ${{ needs.build.outputs.docker_image }}
          TF_VAR_docker_registry_server: ${{ needs.build.outputs.docker_registry_server }}
          TF_VAR_docker_registry_username: ${{ needs.build.outputs.docker_registry_username }}
          TF_VAR_docker_registry_password: ${{ needs.build.outputs.docker_registry_password }}
