name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy infrastructure?'
        required: true
        default: 'false'
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.0.0'

      - name: Azure Login
        run: |
          export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          export ARM_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Create SSH directory if not exists
        run: mkdir -p $HOME/.ssh

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/.ssh/masterchass.pub
        shell: bash

      - name: Terraform Init
        run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}" terraform
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform Apply
        if: ${{ github.event.inputs.destroy != 'true' }}
        run: terraform apply --auto-approve
        working-directory: terraform

      - name: Terraform Destroy
        if: ${{ github.event.inputs.destroy == 'true' }}
        run: terraform destroy --auto-approve
        working-directory: terraform
